version: '2'
services:
  cache:
    build: ./cache
    networks:
      - graphite
    ports:
      - 8080:8080
  statsd:
    image: statsd-common
    ports:
      - 8125:8125/udp
    links:
      - cache:graphite
    networks:
      - graphite
networks:
  graphite:
    driver: bridge
